# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Auth0Sample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Auth0Sample
  pod 'Lock', '~> 1.24'
  pod 'SimpleKeychain', '~> 0.7'
  pod 'Auth0', '~> 1.0.0-beta.2'
end
