# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Auth0Sample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Auth0Sample
  pod 'Auth0', '~> 1.5'
  pod 'Lock', '~> 2.2'
end
